name: Build Reactant_jll

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}


env:
  BINARYBUILDER_AUTOMATIC_APPLE: true
  BINARYBUILDER_RUNNER: privileged
  BINARYBUILDER_USE_CCACHE: true
  JULIA_REGISTRYCI_AUTOMERGE: true
  JULIA_VERSION: '1.7.3'
  BUILD_PROJECT: R/Reactant

jobs:
  define-matrix:
    name: Define matrix
    runs-on: jll

    outputs:
      platforms: ${{ steps.gen-platforms.outputs.platforms }}

    steps:
      - name: Set JULIA_PROJECT
        # We have to use `${GITHUB_WORKSPACE}` instead of `github.workspace` because GitHub
        # is terrible and the two don't match inside containers:
        # https://github.com/actions/runner/issues/2058
        run:
          echo "JULIA_PROJECT=${GITHUB_WORKSPACE}/.ci" >> "${GITHUB_ENV}"
      - name: Cleanup
        timeout-minutes: 5
        shell: bash
        run: |
          if [[ -f ./clean_builds.sh ]]; then
              ./clean_builds.sh
          fi
          if [[ -f ./clean_products.sh ]]; then
              ./clean_products.sh
          fi
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: '${{ env.JULIA_VERSION }}'
      # - name: Load Julia packages from cache
      #   id: julia-cache
      #   uses: julia-actions/cache@v2
      - name: Instantiate environment
        timeout-minutes: 20
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: Generate list of platforms
        id: gen-platforms
        shell: julia --color=yes {0}
        # Adapted from <https://github.com/JuliaPackaging/Yggdrasil/blob/e6019028ad8dafb9507b9d9f4d09d04b11640461/.buildkite/generator.jl>.
        run: |
          TEMP = mktempdir()
          NAME = basename("${{ env.BUILD_PROJECT }}")
          exec(cmd) = @assert success(pipeline(cmd; stderr=stderr, stdout=stdout))
          julia(args) = `$(Base.julia_cmd()) $(args)`

          cd("${{ env.BUILD_PROJECT }}") do
              @info "Generating meta.json..."
              JSON_PATH = "$(TEMP)/$(NAME).meta.json"
              julia(`--compile=min ./build_tarballs.jl --meta-json="$(JSON_PATH)"`) |> exec

              # Generate platforms
              julia(`$(ENV["GITHUB_WORKSPACE"])/.ci/generate_platforms.jl "$(JSON_PATH)" $(TEMP)/$(NAME).platforms.list`) |> exec
          end

          PLATFORMS = split(readchomp(joinpath(TEMP, "$(NAME).platforms.list")))
          if isempty(PLATFORMS)
              @error "Unable to determine the proper platforms" NAME
          end

          platforms = "platforms=[$(join(repr.(PLATFORMS), ','))]"

          open(ENV["GITHUB_OUTPUT"], "a") do io
              println(io, platforms)
          end

  build-platforms:
    name: Build ${{ matrix.platform }}
    runs-on: jll

    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJSON(needs.define-matrix.outputs.platforms) }}

    steps:
      - name: Set JULIA_PROJECT
        # We have to use `${GITHUB_WORKSPACE}` instead of `github.workspace` because GitHub
        # is terrible and the two don't match inside containers:
        # https://github.com/actions/runner/issues/2058
        run:
          echo "JULIA_PROJECT=${GITHUB_WORKSPACE}/.ci" >> "${GITHUB_ENV}"
      - name: Cleanup
        timeout-minutes: 5
        shell: bash
        run: |
          if [[ -f ./clean_builds.sh ]]; then
              ./clean_builds.sh
          fi
          if [[ -f ./clean_products.sh ]]; then
              ./clean_products.sh
          fi
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: '${{ env.JULIA_VERSION }}'
      # - name: Load Julia packages from cache
      #   id: julia-cache
      #   uses: julia-actions/cache@v2
      - name: Instantiate environment
        timeout-minutes: 20
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.instantiate()
      - name: Build Reactant
        run: |
          julia --color=yes --threads=16 build_tarballs.jl --verbose ${{ matrix.platform }}
        working-directory: ${{ env.BUILD_PROJECT }}
      - uses: actions/upload-artifact@v4
        with:
          name: products-${{ matrix.platform }}
          path: ${{ env.BUILD_PROJECT }}/products
          compression-level: 0
          retention-days: 2
      - name: Cleanup
        if: ${{ always() }}
        timeout-minutes: 5
        run: |
          ./clean_builds.sh
          ./clean_products.sh

  register:
    name: Register
    runs-on: jll

    needs: build-platforms

    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v5
        with:
          merge-multiple: true
      - name: Check
        run: |
          pwd
          ls -lhrt
