name: "Build Reactant_jll"

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  build-jll:
    name: Build Reactant_jll
    strategy:
      fail-fast: false
    uses: ./.github/workflows/build-reactant-reusable.yml
